### ISSUE TITLE
Question regarding the 

### ISSUE THREAD

**Issue by isalirezag** [yeephycho/tensorflow_input_image_by_tfrecord#2]
I am trying to use your tutorial.
So in the build_image_data.py file we have the following:

```
tf.app.flags.DEFINE_string('train_directory', './',
                           'Training data directory')
tf.app.flags.DEFINE_string('validation_directory', './',
                           'Validation data directory')
tf.app.flags.DEFINE_string('output_directory', './',
                           'Output data directory')
```

Should I do anything after I do "cd ../tensorflow_input_image_by_tfrecord/src"? Do I need to create folders namely Output data directory, Validation data directory, Training data directory?

When I just run the code as it is explained, I receive the error: 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 110: invalid start byte
`

**Comment by yeephycho** [comment]
Hi @isalirezag ,

Since this repo. presumes that the working environment is under ubuntu, I never tested it under windows or other environment.
One thing I noticed is that the path "./" is current under ubuntu, so I think, you should change the "./" into something like "C://your//output//path". Maybe windows cannot recognize "./".
And you can find the latest build_image_data.py at [tensorflow repo](https://github.com/tensorflow/models/blob/master/inception/inception/data/build_image_data.py).

Try the latest version, It may fit the current tf version better.

With regards!
